server:
  port: 8070
spring:
  datasource:   # 数据源相关配置
    url: jdbc:mysql://localhost:3306/ifknow?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    hikari:
      connection-timeout: 30000                       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                                 # 最小连接数
      maximum-pool-size: 15                           # 最大连接数
      auto-commit: true                               # 自动提交
      idle-timeout: 600000                            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP                   # 连接池名字
      max-lifetime: 1800000                           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

  profiles:

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.ifknow.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml,mapper/*/*.xml      # mapper映射文件

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.ifknow.my.MyMapper
  not-empty: false       #在进行数据库操作的时候，判断表达式 username !=null,是否追加 username!=''
  identity: MYSQL
